### ISSUE TITLE
Telegram Not Installed !!!!

### ISSUE THREAD

**Issue by JonathanOchej** [mank319/elementaryPlus#376]
Hi, i have installed telegram 0.9.24 with the atareao ppa : 
  sudo add-apt-repository ppa:atareao/telegram
  sudo apt-get update'
  sudo apt-get install telegram

But Elementary+ configurator tell me that it's not installed !

I checked source code on repo and found : `"%s/.TelegramDesktop/tdata/icon.png" % (home),` in `elementaryplus-installer.py`

I verified but i dont have this icon on my telegram folder. So i dupplicate the icomute_22_0.png found in ".TelegramDesktop/tdata/ticons" to ".TelegramDesktop/tdata/icon.png"

i launched again Elementary+ configurator and i could "actived" the icon indicator for Telegram.

Maybe you need to update `elementaryplus-installer.py` for put the good path (maybe just a folder path) to check if Telegram is installed.

Ty for your Elementary+ configurator, it rock ;)

**Comment by Elizabeth-Vinogradova** [comment]
Fabulous

**Comment by brainscript** [comment]
#405 should fix it.

**Comment by edipox** [comment]
I still have this issue with Loki. Thank you @JonathanOchej for the solution

**Comment by Milozzy** [comment]
I'm still affect by this bug with Loki
